### ISSUE TITLE
Investigate using Netlify to get HTTPS support

### ISSUE THREAD

**Issue by jordanschalm** [ubclaunchpad/ubclaunchpad.github.io-old#41]
Netlify is a static CDN that has a free tier like GitHub Pages but supports HTTPS. 

I think it looks pretty dumb that we're a tech club but our website doesn't support HTTPS, so we should do this.

**Comment by jordanschalm** [comment]
I went through this process for my personal website and it was really easy! Definitely should go ahead with this for the LP site

**Comment by bobheadxi** [comment]
Isn't it just a matter of deploying this repository to Netlify? Is there anything that has to be done on the code side?

**Comment by jordanschalm** [comment]
Yep, it's all config. No code changes required

**Comment by bfbachmann** [comment]
We can just do this through GitHub Pages 
![image](https://user-images.githubusercontent.com/9647946/38108633-50ac9b32-334a-11e8-855f-f2129c0b3130.png). But first we have to change all the URLs we request stuff from to HTTPS to avoid errors on the client side when loading fonts etc.

**Comment by jordanschalm** [comment]
@bfbachmann It doesn't work with custom domains, just with the `.github.io` domain. https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by bfbachmann** [comment]
That's unfortunate.
