### ISSUE TITLE
root path is not /index-club.html

### ISSUE THREAD

**Issue by MickAvery** [ubclaunchpad/ubclaunchpad.github.io-old#7]
Currently, the root path is `index.html`. However, this does not have the link that takes potential applicants to the google application form. This may be a problem for aspiring applicants who are still taken to `index.html`. The only way to `index-club.html` is through the link posted on the facebook page. I forked the repo hoping to fix this problem by just renaming the files, but then I thought it might mess up other pages that link them.

**Comment by jordanschalm** [comment]
Is this still an issue?
